import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Services from "@/components/Services";
import About from "@/components/About";
import ContactUs from "@/components/ContactUs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Logicraft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen relative overflow-x-hidden`}>
        {/* Cosmic Background */}
        <div className="absolute inset-0 overflow-hidden">
          {/* Base Galaxy Gradient */}
          <div className="absolute inset-0 bg-gradient-to-br from-purple-950 via-indigo-950 to-blue-950" />
          
          {/* Enhanced Stars */}
          <div className="absolute inset-0">
            {[...Array(200)].map((_, i) => {
              const starSize = Math.random() * 3 + 1; // 1px to 4px
              const glowSize = Math.random() * 8 + 4; // 4px to 12px
              return (
                <div
                  key={i}
                  className="absolute bg-white rounded-full"
                  style={{
                    width: `${starSize}px`,
                    height: `${starSize}px`,
                    left: `${Math.random() * 100}%`,
                    top: `${Math.random() * 100}%`,
                    opacity: Math.random() * 0.7 + 0.3,
                    boxShadow: `0 0 ${glowSize}px white`
                  }}
                />
              );
            })}
          </div>

          {/* Nebula Effect */}
          <div className="absolute inset-0 opacity-50 mix-blend-screen">
            <div className="absolute -top-1/4 -left-1/4 w-[150%] h-[150%] bg-gradient-to-r from-purple-600/20 via-transparent to-pink-500/20" />
            <div className="absolute -top-1/3 -right-1/4 w-[150%] h-[150%] bg-gradient-to-br from-indigo-600/15 to-purple-400/15" />
          </div>

          {/* Glowing Orbs */}
          <div className="absolute inset-0">
            <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-purple-600/10 rounded-full blur-3xl" />
            <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-indigo-600/10 rounded-full blur-3xl" />
          </div>

          {/* Space Texture */}
          <div className="absolute inset-0 bg-space-texture opacity-10" />
        </div>

        {/* Content Layer */}
        <div className="relative z-10">
          <Navbar />
          {children}
          <Services />
          <About />
          <ContactUs />
        </div>
      </body>
    </html>
  );
}